# Generated by Django 4.2.3 on 2023-07-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='category',
            field=models.CharField(default='', max_length=256),
        ),
    ]
