# Generated by Django 4.2.3 on 2023-07-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_nft_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='tokenId',
            field=models.IntegerField(default=0),
        ),
    ]
